---

apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: frontpage
spec:
  replicas: 2
  selector:
    matchLabels:
      page: front
  template:
    metadata:
      labels:
        page: front
    spec:
      containers:
        - name: main
          image: nginx:latest

---

apiVersion: batch/v1
kind: Job
metadata:
  name: deletepage
  annotations:
    argocd.argoproj.io/hook: Skip
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      containers:
        - name: run-something
          image: alpine:latest
          command: ["echo", "I am super quickk!!"]
      restartPolicy: Never
