---

apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: frontpage
spec:
  replicas: 1
  selector:
    matchLabels:
      page: front
  template:
    metadata:
      labels:
        page: front
    spec:
      containers:
        - name: main
          image: nginx:latest

---

apiVersion: batch/v1
kind: Job
metadata:
  name: deletepage
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
spec:
  template:
    spec:
      containers:
        - name: run-something
          image: alpine:latest
          command: ["/bin/sh", "-c", "exit 1"]
      restartPolicy: Never
