---

apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: frontpage
spec:
  replicas: 1
  selector:
    matchLabels:
      page: front
  template:
    metadata:
      labels:
        page: front
        color: orange
    spec:
      containers:
        - name: main
          image: nginx:latest


---

apiVersion: batch/v1
kind: Job
metadata:
  name: deletepagee
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      containers:
        - name: run-something
          image: alpine:latest
          # command: ["/bin/sh", "-c", "exit 1"]
          command: ["echo", "hello"]
      restartPolicy: Never
