---

apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: frontpage
spec:
  replicas: 2
  selector:
    matchLabels:
      page: front
  template:
    metadata:
      labels:
        page: front
    spec:
      containers:
        - name: main
          image: nginx:latest

---

apiVersion: batch/v1
kind: Job
metadata:
  name: bookjob
  annotations:
    argocd.argoproj.io/hook: PreSync
spec:
  template:
    spec:
      containers:
        - name: run-something
          image: alpine:latest
          command: ["sleep", "30"]
      restartPolicy: Never
