apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: frontpage
spec:
  replicas: 1
  selector:
    matchLabels:
      page: front
  template:
    metadata:
      labels:
        page: front
    spec:
      containers:
        - name: main
          image: nginx:latest
