
apiVersion: batch/v1
kind: Job
metadata:
  name: bookJob
  annotations:
    argocd.argoproj.io/hook: PreSync
spec:
  template:
    spec:
      containers:
        - name: run-something
        image: alpine:latest
        command: ["sleep", "30"]
